version: "3.8"

services:
  db:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db

  backend:
    build: ./backend
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MONGODB_USERNAME: "root"
      MONGODB_PASSWORD: "root"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ./frontend:/app
volumes:
  mongo-data:
    driver: local
